version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.10
    working_directory: ~/project

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy:
    docker:
      - image: amazon/aws-cli:2.15.15 # AWS CLI with Alpine
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Upload to S3
          command: |
            aws s3 sync ~/project/dist s3://online-bookstore --delete --region eu-central-1

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
